# Generated by Django 2.1 on 2018-09-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180911_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='highest_rating',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='imdb_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='lowest_rating',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='photo_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human',
            name='rotten_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human',
            name='birth_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='human',
            name='death_date',
            field=models.CharField(max_length=100),
        ),
    ]
