# Generated by Django 2.1 on 2018-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180911_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
