# Generated by Django 2.1 on 2018-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_human_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='award',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
