# Generated by Django 2.1 on 2018-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180913_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='profession',
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='index.Crew'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='human',
            field=models.CharField(max_length=100),
        ),
    ]
