# Generated by Django 2.1 on 2018-09-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0009_auto_20180915_2254'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('living_year_from', models.IntegerField(null=True)),
                ('living_year_to', models.IntegerField(null=True)),
                ('profession', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HumanRequestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Human')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.HumanRequest')),
            ],
        ),
    ]
