# Generated by Django 2.1 on 2018-09-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180915_2254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0002_humanrequest_humanrequestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
