# Generated by Django 2.1 on 2018-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_moviesubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanrequest',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='humanrequest',
            name='profession',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='genre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='title',
            field=models.TextField(),
        ),
    ]
